trigger:
  - main

pool:
  vmImage: 'ubuntu-latest'

stages:
  - stage: Build
    displayName: 'Build Stage'
    jobs:
      - job: BuildJob
        displayName: 'Build Job'
        steps:
          - task: UseDotNet@2
            inputs:
              packageType: 'sdk'
              version: '7.x'
              installationPath: $(Agent.ToolsDirectory)/dotnet

         # - script: dotnet restore
         #   displayName: 'Restore NuGet packages'

          - script: dotnet build --configuration Release --no-restore
            displayName: 'Build Solution'

          - script: dotnet test --no-restore --verbosity normal
            displayName: 'Run Unit Tests'

          - task: PublishBuildArtifacts@1
            inputs:
              PathtoPublish: '$(Build.ArtifactStagingDirectory)'
              ArtifactName: 'drop'
              publishLocation: 'Container'

  - stage: Deploy
    displayName: 'Deploy Stage'
    dependsOn: Build
    jobs:
      - job: DeployJob
        displayName: 'Deploy Job'
        steps:
          - download: current
            artifact: drop

          - script: echo "Deploying application..."
            displayName: 'Deployment Step'